# vipies template — Static site (HTML/CSS/JS)
# Nama file: /etc/nginx/sites-available/<domain>
# Struktur: satu blok server. HTTP-only saat belum ada cert,
# certbot menambah 443 + redirect.
server {
    listen 80;
    server_name __DOMAIN__;
    root /var/www/__DOMAIN__;
    index index.html;

    client_max_body_size 128M;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|webp|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
